api_version = "2026-07"

[[extensions]]
type = "ui_extension"
name = "NI Card Terminal"
handle = "ni-terminal"
uid = "a0afbc17-d216-4e61-875a-19d2523083df115f5fa4"
description = "NI card terminal: pay and refund"

[[extensions.targeting]]
module = "./src/Tile.jsx"
target = "pos.home.tile.render"

[[extensions.targeting]]
module = "./src/Modal.jsx"
target = "pos.home.modal.render"

[[extensions.targeting]]
module = "./src/RefundMenuItem.jsx"
target = "pos.order-details.action.menu-item.render"

[[extensions.targeting]]
module = "./src/RefundModal.jsx"
target = "pos.order-details.action.render"

[extensions.capabilities]
network_access = true
